### ISSUE TITLE
Can't send message

### ISSUE THREAD

**Issue by fknMega** [dumptyd/omegle-node#14]
I maked a discord.js bot that works with omegle
So like I can chat on omegle through discord,
But I'm 100% sure that     om.send(message) doesn't work

That's the code of sending message + I added there a command to reconnect

```
bot.on('message',function(message){
    if(message.channel.id !== "755482756187816036") return;
    if(message.content === "!rec") {
        om.disconnect()
        om.connect()
        bot.channels.cache.get('755482756187816036').send('**ReConnected !**');
        return;
    }
    om.send(message)
})
```

The reconnect command is working 100%
But Sending message on omegle is not working

**Comment by fknMega** [comment]
ha and bot. is the discord client
and om. is the omegle client

**Comment by evilfactory** [comment]
@MegaPowerlol  I had a similar issue to the send message function, i had to change the querystring package to an alternative to fix the issue

theres a pull request fixing the issue, but i don't think it will be ever merged

**Comment by evilfactory** [comment]
@MegaPowerlol 

>     om.send(message)

You are sending the message object, you need to send the contents of the message

>     om.send(message.content)

this should fix it

**Comment by fknMega** [comment]
> @MegaPowerlol
> 
> > ```
> > om.send(message)
> > ```
> 
> You are sending the message object, you need to send the contents of the message
> 
> > ```
> > om.send(message.content)
> > ```
> 
> this should fix it

Lol I'm so dumb, how I didn't saw that
