### ISSUE TITLE
Library broken?

### ISSUE THREAD

**Issue by YassienW** [dumptyd/omegle-node#15]
Trying the example [here](https://github.com/dumptyd/omegle-node/blob/master/examples/omegle.js) all i get is this, constantly

```
Connected to server as: central3:3zsp8tnjlpyimlhnxi58kll2w8ja4l
You have disconnected.
Server updated to: front21.omegle.com

Process finished with exit code 0
```
Does the library not work anymore or am i missing something?

**Comment by ghost** [comment]
Works for me.
