### ISSUE TITLE
Errors after connecting

### ISSUE THREAD

**Issue by paleodictyon** [dumptyd/omegle-node#3]
Hi there.

I'm using the example script, but once I get connected, I start getting spammed this error message.

```
Error: getEvents(): Error: getaddrinfo ENOTFOUND front6 front6:80
Error: getEvents(): Error: getaddrinfo ENOTFOUND front6 front6:80
Error: getEvents(): Error: getaddrinfo ENOTFOUND front6 front6:80

```

Am I doing something wrong?

- Node v6.10.3

**Comment by paleodictyon** [comment]
I think it's because Omegle changed the subdomain.

**Comment by dumptyd** [comment]
Hi, thanks for creating the issue. I've pushed a fix for that and published the latest version on npm, let me know if that fixes it for you. :)
