### ISSUE TITLE
Setting up on Glitch

### ISSUE THREAD

**Issue by mragarton** [dumptyd/omegle-node#9]
I'm trying to implement this code into my existing bot running on glitch, but when I run the code on the host it doesn't connect to the server properly.

'connected to the server as: undefined'

I tried to check whether it's a captcha error or not, but it doesn't seem to be that.

**Comment by dumptyd** [comment]
So it only happens there? Does it work locally?

**Comment by mragarton** [comment]
Figured that it's actually Omegle who bans most VPS and web server IP addresses. (Yet they still can't stop those spam bots.)

It does work locally. Sorry for the issue, it has nothing to do with the actual API.
